
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build in linux
        run: |
        ./build.sh
        ./build.sh optimize

  windows_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build in windows
        run: |
        .\\build.bat
        .\\build.bat optimize
